In [349]:
import pandas as pd

In [350]:
import kagglehub

path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/titanic-dataset


In [351]:
cd /kaggle/input/titanic-dataset

/kaggle/input/titanic-dataset


In [352]:
ls

Titanic-Dataset.csv


In [353]:
data = pd.read_csv("/kaggle/input/titanic-dataset/Titanic-Dataset.csv")

In [354]:
data.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [355]:
data = data.drop(['PassengerId', 'Name', 'Cabin', 'Embarked', 'Ticket'], axis=1)

In [356]:
data

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
888         0       3  female   NaN      1      2  23.4500
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[891 rows x 7 columns]

In [357]:
data['Sex'] = data['Sex'].map({'male': 1, 'female':0})

In [358]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [359]:
data = data.dropna()

In [360]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    int64  
 1   Pclass    714 non-null    int64  
 2   Sex       714 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     714 non-null    int64  
 5   Parch     714 non-null    int64  
 6   Fare      714 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 44.6 KB


In [361]:
#Pclass	Sex	Age	SibSp	Parch	Fare

In [362]:
import numpy as np

In [363]:
X = data.iloc[:, 1:7]
X = np.array(X)
y = np.array(data.iloc[:, 0])
y

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [364]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

In [365]:
Xtrain.shape
print(Xtrain[:5])

[[  2.      1.     28.      0.      1.     33.   ]
 [  1.      0.     30.      0.      0.     86.5  ]
 [  3.      1.     19.      0.      0.      6.75 ]
 [  1.      0.     31.      1.      0.    113.275]
 [  1.      1.     65.      0.      0.     26.55 ]]


In [366]:
# Chênh lệch giữa tuổi và giá trị Sibsp, pclass nó quá chênh lệch nhau nên phải dùng scaler
from sklearn.preprocessing import MinMaxScaler

Scaler = MinMaxScaler()
Xtrain = Scaler.fit_transform(Xtrain)
Xtest = Scaler.transform(Xtest)
Xtrain

array([[0.5       , 1.        , 0.37269876, 0.        , 0.16666667,
        0.06441171],
       [0.        , 0.        , 0.39997273, 0.        , 0.        ,
        0.16883676],
       [1.        , 1.        , 0.24996591, 0.        , 0.        ,
        0.01317512],
       ...,
       [1.        , 0.        , 0.29087686, 0.        , 0.        ,
        0.01415106],
       [1.        , 1.        , 0.01813719, 0.8       , 0.16666667,
        0.07746484],
       [1.        , 1.        , 0.45452066, 0.2       , 0.16666667,
        0.02810693]])

In [367]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report # chỉ để hiển thị kết quả
SVM = SVC()
paramGrid = {
    'C' : [0.1, 1, 10],
     'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'degree': [2, 3, 4]

}

In [368]:
gridSearch = GridSearchCV(estimator=SVM,cv=10, param_grid=paramGrid, )
gridSearch.fit(Xtrain, ytrain)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'degree': [2, 3, 4],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [369]:
bestPagram = gridSearch.best_params_
bestScore = gridSearch.best_score_
bestPagram, bestScore

({'C': 10, 'degree': 2, 'kernel': 'poly'}, 0.8161222020568661)

In [370]:
Model = SVC(**bestPagram)
Model.fit(Xtrain, ytrain)

SVC(C=10, degree=2, kernel='poly')

In [371]:
ypre = Model.predict(Xtest)

In [372]:
report = classification_report(ypre, ytest)
print(report)

              precision    recall  f1-score   support

           0       0.86      0.78      0.82        89
           1       0.68      0.80      0.74        54

    accuracy                           0.78       143
   macro avg       0.77      0.79      0.78       143
weighted avg       0.79      0.78      0.79       143



In [373]:
xReality = np.array([1, 1, 19, 2, 1, 71.000])

xReality = Scaler.transform(xReality.reshape(1, -1))
print(xReality)

[[0.         1.         0.24996591 0.4        0.16666667 0.13858277]]


In [374]:
yReality = Model.predict(xReality)

In [375]:
yReality[0]

1